experimental-features = nix-command flakes repl-flake
accept-flake-config = true

# 加速
max-jobs = auto
cores = 0
max-substituter-jobs = 40

# 缓存
substituters = https://cache.nixos.org https://nix-community.cachix.org https://fenix.cachix.org
trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= fenix.cachix.org-1:PpL1UNHViEFrcJzCDV+yl+S+c90I5hTqGq0G+1RP0wM=

# 空间管理
auto-optimise-store = true
min-free = 1G
max-free = 10G

# 允许非自由软件
allow-unfree = true

# 沙盒构建
sandbox = true

# 信任当前用户
trusted-users = root @admin @wheel
